[DNM] Fix processing of power limit file
StarryInternet/mwlwifi pull request #2
Opened 2020-10-29 17:18 UTC by nhed

- The last commit (`Fix undersized`) is the actual fix!
- The first two commits (`Harden parsing`, & `Probably should not release mutex`) address potential issues.
- The third commit (`Add /sys/kernel`) is nice to have but function can be performed with a bash script as well (which I have as).

2020-10-30 17:21 UTC, mtp401 requested changes

2020-10-30 17:21 UTC, mtp401 commented on debugfs.c
> +	int size = (SYSADPT_TXPWRLMT_CFG_BUF_SIZE * 3)+40;
existing style in here is spaces between operators

2020-10-30 17:21 UTC, mtp401 commented on debugfs.c
> +			kfree(buf);
nit: would move this to a clean up label wrapped in a null check

2020-10-30 17:21 UTC, mtp401 commented on debugfs.c
> +	len += scnprintf(p + len, size - len, "01 0E 24 A1\n");
nit: you could use a straight strcpy here and avoid the overhead of format parsing

2020-10-30 17:21 UTC, mtp401 commented on debugfs.c
> +	char *buf = kmalloc(size, GFP_KERNEL);
since you're allowing userspace to read from this i would kzalloc for an extra layer of protection in case `len` is ever accidentally screwed up

2020-10-30 17:21 UTC, mtp401 commented on debugfs.c
> +		__le16 subband_len = le16_to_cpu(subband_hdr->len);
this is a bug on be arches

2020-10-30 17:21 UTC, mtp401 commented on hif/fwcmd.c
> +	*ok = 1;
where is this function used? it would be cleaner / more idiomatic, imo, to either expand the return type to s32 or s16 if the full range of u16 is not needed here and return an error code

2020-11-02 19:27 UTC, nhed commented on debugfs.c
> +	len += scnprintf(p + len, size - len, "01 0E 24 A1\n");
Looking at this I should emit the same constant used for reading (`TXPWRLMT_CFG_SIGNATURE`).

2020-11-02 19:28 UTC, nhed commented on debugfs.c
> +	len += scnprintf(p + len, size - len, "01 0E 24 A1\n");
But also not sure that this efficiency warrants steering from what the rest of the module does

2020-11-03 14:51 UTC, mtp401 submitted a review, later dismissed

2026-02-12 23:14 UTC, closed without merging